token       = "5oUip1iGiwl_ZMr9E_XaffHrPRbaLVKFa5SN5clpsO9MB"
region      = "ap-southeast-2"
profile     = "default"
account     = "account-BjpMI73W"
workspace   = "workspaceggD9LoaL"
bluexp_cred = "aws_fsx"